#!/usr/bin/env python3
"""
convert_docs.py — Convert Markdown docs to reStructuredText (RST)
and generate a hidden _auto_toc.rst file to include in Sphinx builds.

Run inside your Sphinx Docker build before calling `make html`.
"""

import pathlib
import subprocess
import sys
import time

# ---------------------------------------------------------------------
# Configuration
# ---------------------------------------------------------------------
here = pathlib.Path(__file__).resolve().parent
root = here.parent.parent  # project root
md_dir = root / "docs"
rst_dir = here.parent / "source" / "converted"
AUTO_TOC_FILENAME = "_auto_toc.rst"


# ---------------------------------------------------------------------
# Utilities
# ---------------------------------------------------------------------
def log(msg: str):
    """Print a message with a consistent prefix."""
    print(f"\033[96m[convert_docs]\033[0m {msg}")


def run_pandoc(md_path: pathlib.Path, out_path: pathlib.Path) -> bool:
    """Convert one Markdown file to RST using Pandoc."""
    try:
        title = md_path.stem.replace("-", " ").title()
        subprocess.run(
            [
                "pandoc",
                "-f",
                "markdown",
                "-t",
                "rst",
                "--metadata",
                f"title={title}",
                str(md_path),
                "-o",
                str(out_path),
            ],
            check=True,
            stdout=subprocess.PIPE,
            stderr=subprocess.PIPE,
        )
        return True
    except subprocess.CalledProcessError as e:
        log(f"\033[91mError:\033[0m Pandoc failed on {md_path}")
        print(e.stderr.decode() or e.stdout.decode())
        return False


# ---------------------------------------------------------------------
# Generate hidden _auto_toc.rst (dynamic, per section)
# ---------------------------------------------------------------------


def generate_auto_toc(rst_dir: pathlib.Path, AUTO_TOC_FILENAME: str):
    """
    Write an _auto_toc.rst with an explicit list of every .rst file
    under the converted/ tree. No globs, no captions, no hidden magic.
    """
    toc_path = rst_dir.parent / AUTO_TOC_FILENAME
    log(f"\nGenerating explicit TOC file: {toc_path}")

    # Collect all converted RST files, sorted
    all_rst = sorted([p for p in rst_dir.rglob("*.rst") if p.name != AUTO_TOC_FILENAME])

    lines = [
        ".. This file is auto-generated by convert_docs.py",
        ".. Do not edit manually — changes will be overwritten.",
        "",
        ".. toctree::",
        "   :maxdepth: 2",
        "   :hidden:",
        "",
    ]

    for rst_file in all_rst:
        # Compute path relative to Sphinx source root (the directory ABOVE converted/)
        rel = rst_file.relative_to(rst_dir.parent)
        # Use forward slashes for Sphinx
        lines.append(f"   {rel.as_posix()}")

    lines.append("")

    toc_path.write_text("\n".join(lines), encoding="utf-8")
    log(f"Wrote explicit TOC with {len(all_rst)} entries → {toc_path}")


def generate_auto_toc_does_not_work_wasted_hours(rst_dir: pathlib.Path, AUTO_TOC_FILENAME: str):
    toc_path = rst_dir.parent / AUTO_TOC_FILENAME
    log(f"\nGenerating toctree file: {toc_path.relative_to(rst_dir.parent)}")

    sections = sorted(p for p in rst_dir.iterdir() if p.is_dir())

    lines = [
        ".. This file is auto-generated by convert_docs.py",
        ".. Do not edit manually — changes will be overwritten.",
        "",
    ]

    # Hidden toctree for each top-level directory
    for section in sections:
        section_name = section.name.replace("-", " ").title()
        lines += [
            ".. toctree::",
            "   :maxdepth: 1",
            "   :hidden:",
            "   :glob:",
            f"   :caption: {section_name}",
            "",
            # Prefix so Sphinx finds them relative to source/
            f"   {section.name}/**/*.rst",
            "",
        ]

    # Include any loose top-level .rst files (like whatsnew.rst)
    loose_files = [f.name for f in rst_dir.glob("*.rst") if f.name != AUTO_TOC_FILENAME]
    if loose_files:
        lines += [
            ".. toctree::",
            "   :maxdepth: 1",
            "   :hidden:",
            "   :caption: Misc",
            "",
        ]
        for f in loose_files:
            lines.append(f"   {f}")
        lines.append("")

    toc_path.write_text("\n".join(lines), encoding="utf-8")
    log(f"Wrote dynamic toctree with {len(sections)} sections and {len(loose_files)} loose files.")


# ---------------------------------------------------------------------
# Main pipeline
# ---------------------------------------------------------------------
def main():
    start = time.time()
    log("Starting Markdown → RST conversion.")
    log(f"Source: {md_dir}")
    log(f"Output: {rst_dir}")

    if not md_dir.exists():
        log(f"\033[91mError:\033[0m Markdown directory not found: {md_dir}")
        sys.exit(1)

    rst_dir.mkdir(parents=True, exist_ok=True)
    md_files = list(md_dir.rglob("*.md"))
    if not md_files:
        log("No Markdown files found.")
        return

    successes, failures = 0, 0
    for md in md_files:
        if md.name.lower() == "index.md":
            log(f"Skipping index file: {md}")
            continue

        rel = md.relative_to(md_dir)
        out = rst_dir / rel.with_suffix(".rst")
        out.parent.mkdir(parents=True, exist_ok=True)

        log(f"Converting {rel}")
        if run_pandoc(md, out):
            successes += 1
        else:
            failures += 1

    # generate_auto_toc(rst_dir, AUTO_TOC_FILENAME)

    elapsed = time.time() - start
    log(f"\n✅ Conversion complete: {successes} succeeded, {failures} failed.")
    log(f"🕓 Finished in {elapsed:.1f}s.")


# ---------------------------------------------------------------------
if __name__ == "__main__":
    main()
