[testenv:bootstrap]
deps =
    jinja2
    tox
skip_install = true
commands =
    python ci/bootstrap.py --no-env
passenv =
    *

; a generative tox configuration, see: https://tox.wiki/en/latest/user_guide.html#generative-environments
[tox]
envlist =
    clean,
    check,
    docs,
    {py310,py314},
    report
ignore_basepython_conflict = true

[testenv]
basepython =
    py310: {env:TOXPYTHON:python3.10}
    py314: {env:TOXPYTHON:python3.14}
    {bootstrap,clean,check,report,docs,codecov}: {env:TOXPYTHON:python3.12}
setenv =
    PYTHONPATH={toxinidir}/tests
    PYTHONUNBUFFERED=yes
    cover: SETUPPY_EXT_COVERAGE=yes
passenv =
    *
usedevelop = false
deps =
    pytest
    pytest-cov
    llvmlite
    numba
commands =
    {posargs:pytest --cov --cov-report=term-missing --cov-report=xml -vv tests}

[testenv:check]
deps =
    uv
    twine
    docutils
    pre-commit
    readme-renderer
    pygments
    isort
skip_install = true
commands =
    uv build
    twine check dist/*.whl dist/*.tar.gz
    pre-commit run --all-files --show-diff-on-failure

[testenv:docs]
usedevelop = true
extras =
    docs
setenv =
    PIP_INDEX_URL=https://packages.idmod.org/artifactory/api/pypi/pypi-production/simple
commands =
    mkdocs build

[testenv:report]
deps =
    coverage
skip_install = true
commands =
    coverage report
    coverage html

[testenv:clean]
commands =
    python -c "import shutil; [shutil.rmtree(p, ignore_errors=True) for p in ('build', 'dist')]"
    coverage erase
skip_install = true
deps =
    coverage
