name: MkDocs Build on PR

on:
  pull_request:
    branches: [ master, main ]  # Replace with your desired branches

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0  # v7.0.0

    - name: Set up Python
      uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405  # v6.2.0
      with:
        python-version: '3.12'

    - name: Install MkDocs and dependencies
      run: |
        pip install --index-url https://packages.idmod.org/artifactory/api/pypi/pypi-production/simple -e ".[docs]"

    - name: Build MkDocs site
      run: mkdocs build
